In [2]:
print("a")

a


Merhaba
Herhangi baska seyler de yazilabilir(Markdown kismi)

In [9]:
Neden Numpy?

Object `Numpy` not found.


In [11]:
#a=[1,2,3,4]
#b=[2,3,4,5]

In [9]:
import numpy as np

In [5]:
#a=np.array([1,2,3,4])
#b=np.array([2,3,4,5])

In [49]:
#a*b


In [19]:
type(a)


numpy.ndarray

In [11]:
np.array([3.14,4,2,13]) #icinde bi tane ondalikli olursa hepsini ondalikliya cevirecek sekilde yazdirir

array([ 3.14,  4.  ,  2.  , 13.  ])

In [25]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.array([3.14,4,2,13], dtype = "int") #hepsini int yapariz

array([ 3,  4,  2, 13])

In [27]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [33]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [35]:
np.linspace(0,1,10) #10 esit aralikli sayi olusturma 0 ile 1 arasinda

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
np.random.normal(10,4,(3,4)) #ortalama 10 standart sapma 4

array([[15.49732654,  8.00568894, 10.05942203,  6.78918447],
       [12.54641372,  7.49059405,  5.17370827,  7.06689541],
       [ 8.5231148 ,  9.6393603 ,  8.41701686,  1.3880211 ]])

In [39]:
np.random.randint(0,10,(3,3))

array([[7, 9, 3],
       [2, 6, 0],
       [1, 2, 7]])

In [41]:
np.random.randint(10,size=10)

array([1, 8, 5, 5, 5, 7, 6, 8, 5, 7])

In [43]:
#ndim boyut sayisini verir bize
a=np.random.randint(10,size = 10)
a.ndim

1

In [45]:
a.shape #boyut bilgisi

(10,)

In [47]:
a.size #eleman sayisi 10
a.dtype #tipini verir

dtype('int64')

In [65]:
b=np.random.randint(10,size=(3,5))

In [59]:
b.ndim

2

In [57]:
b.shape

(3, 5)

In [61]:
b.size

15

In [55]:
b.dtype

dtype('int64')

In [67]:
b

array([[5, 5, 6, 4, 5],
       [8, 6, 0, 1, 3],
       [1, 6, 9, 9, 0]])

In [77]:
np.arange(1,10).reshape((3,3)) #reshape3 e 3luk bi matrix yapti mesela

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
import numpy as np
x = np.array([1,2,3])
y= np.array([4,5,6])


In [5]:
np.concatenate([x,y]) #birlestirme islemi

array([1, 2, 3, 4, 5, 6])

In [18]:
#iki boyutlu 
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
np.concatenate([a,a],axis=1) #axis 1 olunca sutunlar boyu birlestir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [24]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
x=np.array([1,2,3,99,99,3,2,1])

In [15]:
np.split(x,[3,5]) #diziyi 3 ve 5 indesklerinden ayirir

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [17]:
#soyle de yazabilir
a,b,c=np.split(x,[3,5])

In [19]:
a

array([1, 2, 3])

In [21]:
b

array([99, 99])

In [23]:
c

array([3, 2, 1])

In [25]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.vsplit(m,[2]) #ikiye boldu

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [29]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [31]:
#sorting
v = np.array([2,1,4,3,5])
np.sort(v)

array([1, 2, 3, 4, 5])

In [33]:
m=np.random.normal(20,5,(3,3)) #20 sayilarin ortalamasi
#4 standart deviation

In [35]:
m

array([[25.61294733, 14.72550456, 20.13315726],
       [23.43912125, 23.49563033, 21.10357565],
       [19.21739148, 19.03663362, 20.49470274]])

In [41]:
a=np.random.randint(10,size=(3,5))
a

array([[3, 2, 1, 1, 5],
       [3, 9, 2, 4, 8],
       [5, 4, 8, 0, 1]])

In [43]:
a[1,1]

9

In [45]:
a[1,1]=2.2 #ondalikli yazsak bile int donusturcek 9 u 2 yapicak

In [47]:
a

array([[3, 2, 1, 1, 5],
       [3, 2, 2, 4, 8],
       [5, 4, 8, 0, 1]])

In [51]:
e=np.arange(20,30)
e

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
e[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [55]:
e[1::2]

array([21, 23, 25, 27, 29])

In [59]:
#iki boyutlular
m=np.random.randint(10,size=(5,5))

In [61]:
m

array([[8, 5, 7, 0, 8],
       [3, 9, 6, 9, 5],
       [2, 5, 1, 3, 7],
       [7, 9, 3, 9, 7],
       [7, 9, 9, 9, 6]])

In [63]:
m[:,1]

array([5, 9, 5, 9, 9])

In [65]:
m[0,:]

array([8, 5, 7, 0, 8])

In [67]:
m[0:2,0:3]

array([[8, 5, 7],
       [3, 9, 6]])

In [71]:
m[::,:2]

array([[8, 5],
       [3, 9],
       [2, 5],
       [7, 9],
       [7, 9]])

In [73]:
m[1:3,0:2]

array([[3, 9],
       [2, 5]])

In [77]:
#alt kume ile calismak
a=np.random.randint(10,size=(5,5))
a

array([[7, 7, 5, 6, 4],
       [5, 9, 8, 7, 4],
       [2, 3, 5, 9, 7],
       [8, 1, 9, 9, 4],
       [8, 5, 2, 1, 4]])

In [79]:
alt_a = a[0:3,0:2]
alt_a

array([[7, 7],
       [5, 9],
       [2, 3]])

In [81]:
alt_a[0,0]=99999
alt_a[1,1] = 888

In [83]:
alt_a

array([[99999,     7],
       [    5,   888],
       [    2,     3]])

In [85]:
m=np.random.randint(10,size=(5,5))
m

array([[9, 2, 4, 4, 5],
       [5, 1, 3, 3, 7],
       [9, 2, 1, 5, 3],
       [5, 1, 8, 8, 2],
       [7, 1, 9, 5, 3]])

In [89]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[9, 2],
       [5, 1],
       [9, 2]])

In [91]:
alt_b[0,0] = 9999

In [93]:
alt_b

array([[9999,    2],
       [   5,    1],
       [   9,    2]])

In [11]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [13]:
al_getir=[1,3,5]

In [15]:
v[al_getir] #tek tek yazdirmaktansa boyle yapialbilir

array([ 3,  9, 15])

In [101]:
v=np.array([1,2,3,4,5])

In [103]:
v < 3

array([ True,  True, False, False, False])

In [105]:
v[v<3]

array([1, 2])

In [107]:
v[ v!=3]

array([1, 2, 4, 5])

In [109]:
v=np.array([1,2,3,4,5])

In [113]:
v-1 # aynisini np.subtract(v,1) yazarak elde edebiliriz
#np.sum toplama np.multiply carpma np.divide bolme vs

array([0, 1, 2, 3, 4])

In [115]:
# v**3 ile np.power(v,3) ayni sey

In [117]:
# kalan bulma olay
v%2

array([1, 0, 1, 0, 1])

In [119]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [121]:
np.absolute(np.array([-3])) #mutlak deger

array([3])

In [128]:
np.sin(360)

0.9589157234143065

In [130]:
a=np.array([[5,1],[1,3]])

5x0 + x1 =12
x0+3x1 =10

In [133]:
b=np.array([12,10])

In [135]:
x=np.linalg.solve(a,b)
x #x0 ve x1 degerlerini boyle bu komutla buluyoruz

array([1.85714286, 2.71428571])